sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: F+Ii03IXb8gBth8+jZQMgHfSVovfWZkd8wwdqljvmF9N0TnXkIxvi+orNw10dmdUDXusvQnd0dIkd3aDvP60CmuxwwQpykQON5WKzdLRGX1PB/BIa67rcCWhkL7toFS6vaAkY5cuLuq7DJ2JS9f+vQVXiDH+oGCRrlCGR6LtvhWKxfCAnnDSuAJ8Ivmje1kLvcrC32PdwYj451M0Ug4LeKQKNeHcsoin92YonLKjg1+l0uM8j6ziBBMKba4XPec/fULyF04i9KmK+0SexDk0OjpZF7rLAdUipaC3AIhleiBorCvlIrG2qxyAlWjnkBSIU/C54o5BRxcXNwglIdJbmmIAhB+l9BPa0cF6WuQxiL6ihFuWeP9636TUZdqusEQT0iC5LOAVO4jWBO6j/KzEUb5lAaeXcPq6UpJg09LH4ZL52rxYL5zXl+98wBG7CzGf6uOwNv6Vtiskqi4f4yVobCBXVgGzIzapDB6dXI7lcz2PZH/+ahtdJDuba98q+6gbBmwQVGeegREGn2G0O9HP03O+C5VBxbOxRpoj3rSpvfZrVnFi2azo2cAf5K9oH029FQTTjUef0NwqEEB3dx+A3x7/kLqsJI9rH1r4JF4n0SJ2+KibQn94JpuK/JJpnfI4QYr+7QiVgv9i4dcHDSh3TH97Mvzt0Jva3n+zGpGAxDc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Saint-s-Progress_2683
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy